package org.getfin.modelos.enums;

public enum CategoriaProducto {
    HERRAMIENTAS, INSUMOS, QUIMICOS, VETERINARIOS, ALIMENTACION, SEMILLAS,
    FERTILIZANTES, MAQUINARIA, CONSTRUCCION, COMBUSTIBLES, SEGURIDAD, ADMINISTRATIVO

}