package org.getfin.modelos.enums;

public enum CategoriaCultivo {
    GRANOS_BASICOS, LEGUMBRES, VERDURAS, VEGETALES, FRUTALES, TUBERCULOS,
    CEREALES, FORRAJES, AROMATICAS, MEDICINALES, INDUSTRIALIZABLES
}