package org.getfin.modelos.enums;

public enum EstadoCultivo {
    PREPARACION, SIEMBRA, GERMINACION, CRECIMIENTO, DESARROLLO,
    FLORACION, FRUCTIFICACION, MADURACION, COSECHADO, POSTCOSECHADO, INACTIVO
}